### ISSUE TITLE
P3 Submission Test Results not finding files

### ISSUE THREAD

**Issue by beninato8** [tylerharter/cs320#17]
In the Test Results of my P3 submission, I'm getting a bunch of `FileNotFoundError: [Errno 2] No such file or directory` errors. I think the grader may be ignoring some of the files in my submitted p3.zip. All of the following files are needed for my Flask app to work. Is there any reason that I would be unable to access any of these files from main.py when my code is being tested?
```
.
├── main.py			# main flask app
├── filter_df.py		# handle calls to my API
├── toggl.py			# get new version of main.csv
├── markdown2.py		# library (not my code) to convert markdown to html
├── latest.json			# keep track of last API call
├── main.csv			# cached csv
├── markdown			# markdown to build each page
│   ├── api.md
│   ├── browse.md
│   ├── donate.md
│   └── home.md
├── static			# flask needs a static folder
│   ├── css
│   │   └── main.css		# github markdown css
│   └── images
│       └── favicon.ico 	# favicon
└── templates			# html templates
    ├── home.html
    └── layout.html
```

**Comment by tylerharter** [comment]
Just to confirm, test.py gets 100% when you run it on your VM?  Also, I'm assuming you've checked that those .md files are in the .zip?

**Comment by beninato8** [comment]
I forgot the `-r` flag in my zip target. Oops. tester.py was getting 100%, but that was since I was calling it while in a working directory containing the unzipped files, which means it was running the main.py in the directory it was in.
