### ISSUE TITLE
Deque is pronounced "Deck"

### ISSUE THREAD

**Issue by beninato8** [tylerharter/cs320#7]
From Python's [collections docs](https://docs.python.org/3/library/collections.html#deque-objects):

> Deques are a generalization of stacks and queues (**the name is pronounced “deck”** and is short for “double-ended queue”). Deques support thread-safe, memory efficient appends and pops from either side of the deque with approximately the same O(1) performance in either direction.

From [StackOverflow](https://english.stackexchange.com/questions/226954/how-is-deque-commonly-pronounced)

> It's pronounced /dɛk/, just like the word *deck*, as in a deck of cards.

This answer quotes the great Donald Knuth's *[The Art of Computer Programming](https://ia801608.us.archive.org/11/items/B-001-001-249/B-001-001-249.pdf)* volume 1, section 2.2.1 "Stacks, Queues, and Deques" (page 239):

> Linear lists in which insertions, deletions, and accesses to values occur almost
always at the first or the last node are very frequently encountered, and we give them special names:
> - A *stack* is a linear list for which all insertions and deletions (and usually all accesses) are made at one end of the list. 
> - A *queue* is a linear list for which all insertions are made at one end of the
list; all deletions (and usually all accesses) are made at the other end. 
> - A *deque* (‘"double-ended queue”) is a linear list for which all insertions and
deletions (and usually all accesses) are made at the ends of the list.

> A deque is therefore more general than a stack or a queue; it has some properties
in common with a deck of cards, and it is pronounced the same way.

**Comment by tylerharter** [comment]
Thanks!
